### ISSUE TITLE
Global Filter

### ISSUE THREAD

**Issue by mbowman6241** [mariuszfoltak/angular2-datatable#106]
In your data-filter pipe example in the plunker demo it only shows how to filter off of a single column, row.name. Is their a way to filter the entire table, all columns?

**Comment by mbowman6241** [comment]
If anyone is curious this is the solution that I am using. Not sure if this is the right way but it is working....

```
export class DataFilterPipe implements PipeTransform {
    transform(array: any[], query: string): any {
        if (query) {
            return _.filter(array, row =>
                row.installDate.indexOf(query) > -1 ||
                row.environment.indexOf(query) > -1 ||
                row.userName.indexOf(query) > -1 ||
                row.hostName.indexOf(query) > -1);
        }
        return array;
    }
}
```

**Comment by pacozevallos** [comment]
How can I make it so that it does not distinguish between uppercase and lowercase?
