### ISSUE TITLE
Invalid address to files

### ISSUE THREAD

**Issue by shoudaos** [mariuszfoltak/angular2-datatable#11]
WARNING in ./~/angular2-datatable/lib/DataTable.js
Cannot find source file '../src/DataTable.ts': Error: Cannot resolve 'file' or 'directory' ../src/DataTable.ts in D:\projects\sing\node_modules\angular2-datatable\lib

WARNING in ./~/angular2-datatable/lib/DefaultSorter.js
Cannot find source file '../src/DefaultSorter.ts': Error: Cannot resolve 'file' or 'directory' ../src/DefaultSorter.ts in D:\projects\sing\node_modules\angular2-datatable\lib

WARNING in ./~/angular2-datatable/lib/Paginator.js
Cannot find source file '../src/Paginator.ts': Error: Cannot resolve 'file' or 'directory' ../src/Paginator.ts in D:\projects\sing\node_modules\angular2-datatable\lib

WARNING in ./~/angular2-datatable/lib/BootstrapPaginator.js
Cannot find source file '../src/BootstrapPaginator.ts': Error: Cannot resolve 'file' or 'directory' ../src/BootstrapPaginator.ts in D:\projects\sing\node_modules\angular2-datatable\lib

**Comment by shoudaos** [comment]
src folder doesn't exist, only lib folder

**Comment by mariuszfoltak** [comment]
Yes, it's true. In next release I'll add sources to library files.

**Comment by mariuszfoltak** [comment]
From version 0.3.0 sources are included in package.
