### ISSUE TITLE
Plan of upgrade to RC 1 ? 

### ISSUE THREAD

**Issue by lkc513** [mariuszfoltak/angular2-datatable#12]
Hi

May i know do you'll will have a quick plan to upgrade the current angular2-datatable support rc.1 version? 

I do have some issue on the after upgraded to rc.1 version

Thank You :)

**Comment by mariuszfoltak** [comment]
Yes, version 0.4.0 will be compatible with rc version. I'm working on it now. Version 0.4.0 should be available in few days (max end of the week).

**Comment by lkc513** [comment]
Good to hear that. 
Looking forward to your new release.

**Comment by mariuszfoltak** [comment]
New version (v0.4.2) is already released.
