### ISSUE TITLE
mfDefaultSorter for numeric types

### ISSUE THREAD

**Issue by vosecek** [mariuszfoltak/angular2-datatable#121]
`<mfDefaultSorter by="id">ID</mfDefaultSorter>` sorts alphabetically (1,11,12...,2,21), not as number (1,2,3 ...,11,12).

Maybe add a param `type` to mfDefaultSorter?

**Comment by vosecek** [comment]
My fault, _.orderBy() inside orders according to data type :-), so converting to number helped.

**Comment by nehal076** [comment]
How did you convert to number?
