### ISSUE TITLE
Click Event Support

### ISSUE THREAD

**Issue by shreel2015** [mariuszfoltak/angular2-datatable#13]
Any possibilities of including click event support inside the datatable ?
ie. 
`<td><button (click)="clickMe()">Click !!</button></td>`

**Comment by mariuszfoltak** [comment]
It should work. On project I'm working now, we are using events in table rows and everything works.

Are you getting any error?

**Comment by shreel2015** [comment]
Yes I am getting the following error :

angular2-polyfills.js:267 Uncaught EXCEPTION: Error during evaluation of "click"
ORIGINAL EXCEPTION: TypeError: l_context.clickMe is not a function
ORIGINAL STACKTRACE:
TypeError: l_context.clickMe is not a function
    at AbstractChangeDetector.ChangeDetector_App_1.handleEventInternal (viewFactory_App:591:26)
    at AbstractChangeDetector.handleEvent (http://localhost:3000/node_modules/angular2/bundles/angular2.js:9833:25)
    at AppView.triggerEventHandlers (http://localhost:3000/node_modules/angular2/bundles/angular2.js:10511:34)
    at eval (viewFactory_App:718:94)
    at http://localhost:3000/node_modules/angular2/bundles/angular2.js:13979:34
    at http://localhost:3000/node_modules/angular2/bundles/angular2.js:13407:18
    at ZoneDelegate.invoke (http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:332:29)
    at Object.NgZoneImpl.inner.inner.fork.onInvoke (http://localhost:3000/node_modules/angular2/bundles/angular2.js:2216:31)
    at ZoneDelegate.invoke (http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:331:35)
    at Zone.runGuarded (http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:241:48)
ERROR CONTEXT:
[object Object]Zone.runTask @ angular2-polyfills.js:267ZoneTask.invoke @ angular2-polyfills.js:431

My code is as follows : 

`<tr *ngFor="#item of mf.data">
     <td>{{item.name}}</td>
     <td>{{item.email}}</td>
     <td class="text-right">{{item.age}}</td>
     <td>{{item.city | uppercase}}</td>
     <td><button (click)="clickMe()">Click</button></td>
 </tr>`

`import {Component} from 'angular2/core';
import {bootstrap} from 'angular2/platform/browser';
import {DatePipe} from "angular2/common";
import {HTTP_PROVIDERS, Http} from "angular2/http";
import {DataTableDirectives} from 'angular2-datatable/datatable';


@Component({
    selector: 'app',
    templateUrl: 'src/app.html',
    providers: [HTTP_PROVIDERS],
    directives: [DataTableDirectives],
    pipes: [DatePipe]
})
export class App {

    clickMe() {
      console.log("xyz");
    }

    private data = [];

    constructor(private http: Http) {
        http.get("/src/data.json")
            .subscribe((data)=>{
                this.data = data.json();
            });
    }

    private toInt(num:string) {
        return +num;
    }

    private sortByWordLength = (a: any) => {
        return a.name.length;
    }

}

bootstrap(App);`

**Comment by mariuszfoltak** [comment]
Check this [example](https://plnkr.co/edit/b9PfLQ?p=preview), everything works. Maybe you have problem with angular version or configuration.

**Comment by shreel2015** [comment]
Thank you. Yes, it was angular2 version issue. Now working fine at my end too, thanks.
