### ISSUE TITLE
Add search

### ISSUE THREAD

**Issue by ridaKourchal** [mariuszfoltak/angular2-datatable#17]
Hi my friend 

How i can add search on this datatable ?
thanks advance

**Comment by mariuszfoltak** [comment]
Hi, 
Datatable component doesn't support filtering right now. I would like to add this feature in future.

You can try filtering input array, maybe using lodash, and then display table

**Comment by mariuszfoltak** [comment]
Can you give me some example? It should refresh automatically.

**Comment by ridaKourchal** [comment]
For exemple in search control i write something, and the process execute but the result showing :
section 1 => 2 result,
section 2 => 0
section 5 => 8 result

**Comment by ridaKourchal** [comment]
You said lodash, how to work with it?

**Comment by mariuszfoltak** [comment]
Here is working example: http://plnkr.co/edit/grhag1P85teN4ftggkms?p=preview
Unfortunately, if you are using pipes, component are acting strange. I am marking this as a bug, and I will check it later.

**Comment by ridaKourchal** [comment]
thanks

**Comment by mariuszfoltak** [comment]
Issue solved in version 0.5.0
