### ISSUE TITLE
systemjs and webpack examples both broken

### ISSUE THREAD

**Issue by AaronNGray** [mariuszfoltak/angular2-datatable#19]
both the systemjs and webpack examples seem to be broken for different reasons both on Linux and on Windows

**Comment by TeodorKolev** [comment]
Same here

**Comment by agatsoh** [comment]
Any update on this one.

**Comment by mariuszfoltak** [comment]
I fixed systemjs example and now it should works. And I remove webpack example because I never started doing it.
