### ISSUE TITLE
Cant have multiple tables in view

### ISSUE THREAD

**Issue by Feather-CMS** [mariuszfoltak/angular2-datatable#21]
Hi.
Thanks for your cool code, I cant seem to be able to add more than one table on the view as the second table data overrides the first.
Any suggestions on how to solve this?
Paulo

**Comment by alexjpujol** [comment]
+1 to this

**Comment by mariuszfoltak** [comment]
Hi,
It works, but every datatable must be assigned to different ref-var, eg. `<table ... #mf2="mfDataTable"`>
Link to working example: http://plnkr.co/edit/8lKfz3?p=preview

**Comment by alokstar** [comment]
Hi,
I tried your solution, it works but I am having different issue. When I click on any of the table header, both the table data is getting sorted. I don't know what I am missing or doing wrong. Can you please suggest?
