### ISSUE TITLE
Display of mfBootstrapPaginator cannot be changed using css

### ISSUE THREAD

**Issue by christophebiomedecine** [mariuszfoltak/angular2-datatable#26]
I've tried many ways to change the display of mfBootstrapPaginator without success.

As written, I've retrieved bootstrap css containing navigation and child style, no effect.

Even setting a global style for : 
li {
  display: inline;
}
works on every nav ul li of the page but the nav ul li in mfBootstrapPaginator remains with no style.

I've extract the code from the component mfBootstrapPaginator   : 

```<nav class="pagination">
            <li class="disabled">
                <a style="cursor: pointer">&laquo;</a>
            </li>
	     <li class="active">
                <a style="cursor: pointer">1</a>
            </li><br>
	     <li><br>
                <a style="cursor: pointer">2</a>
            </li><br>
            <li><br>
                <a style="cursor: pointer">&raquo;</a>
            </li><br>
 </nav>```

works, so the style is well displayed but not included in the mfBootstrapPaginator.

**Comment by kgidwani** [comment]
+1
I am also having same issue.

**Comment by mariuszfoltak** [comment]
You can change it by css, but you must overwrite css from bootstrap. Like 
```css
.pagination li a {
    background-color:#eaa;
}
```
Check [this plunker](http://plnkr.co/edit/zfmEeuOxb2tLQ7YcbB6D?p=preview) for example. Style has been added to `header` tag in `index.html` file.

**Comment by SmashedBird** [comment]
Same Problem. Please re-open. The reason is Bootstrap uses a different structure for the pagination.

<nav aria-label="Page navigation">
  <ul class="pagination">
    <li class="page-item"><a class="page-link" href="#" aria-label="Previous"></a></li>
    <li class="page-item"><a class="page-link" href="#">1</a></li>
    <li class="page-item"><a class="page-link" href="#">2</a></li>
    <li class="page-item"><a class="page-link" href="#" aria-label="Next"></a></li>
  </ul>
</nav>

Instead of 

<nav class="pagination">
            <li><a></a></li>
            <li><a></a></li>
</nav>

**Comment by paragsh** [comment]
Yes as @SmashedBird mentioned CSS has changed .

use : 


`
/deep/ .pagination > .active > a 
{
background-color: pink;
}
`

This worked for me.

**Comment by shiv-chaturvedi-94** [comment]
Please reopen this
not clear where to keep the last line 
/deep/ .pagination > .active > a { background-color: pink; }

tried keeping in css file. not working
