### ISSUE TITLE
Upgrade for RC6

### ISSUE THREAD

**Issue by jtc10005** [mariuszfoltak/angular2-datatable#27]
I upgraded a project of mine to RC6.  
This caused me to move my import from my component to module which throws this error: 
`Uncaught Error: Unexpected directive 'DataTable' imported by the module 'TableModule'`

**Comment by taguan** [comment]
As this repository doesn't seem to be active anymore, I forked it, upgraded it to angular 2.0.1 and released a npm package name angular2-datable2
