### ISSUE TITLE
Cascade Dropdownlist

### ISSUE THREAD

**Issue by lkc513** [mariuszfoltak/angular2-datatable#28]
Hi

Anyone experiencing the cascade dropdown issue ?

I do a cascade dropdown in the row by using "onchange", unfortunately it could not able to detect by selecting row and affected others row cascade dropdown data not accuracy anymore... 

Anyone have any idea or solution mind to share ? 

thanks

**Comment by lkc513** [comment]
solution found... 
close case...

**Comment by askaFed** [comment]
@lkc513 
could you tell more about your solution?
