### ISSUE TITLE
Issue with pagination

### ISSUE THREAD

**Issue by kgidwani** [mariuszfoltak/angular2-datatable#33]
Hello,

We are using datatable with pagination to display data in our application.
We also have a search input box that takes input and based on that input we filter the data in the table.
The above functionality works fine when we are on the first page of the pagination. BUT when we are on any other page (other than page 1) the search functionality doesn't work.
We get any empty table displayed even though the search list is not empty.

After debugging we saw that mf.data is empty for the above scenario. (mf.inputData has correct search result data)

Regards,
Kapil

**Comment by dattaghuge1** [comment]
Same search issue is present on plunker demo created by mariuszfoltak. (Try to Filter from 2nd page)
http://plnkr.co/edit/grhag1P85teN4ftggkms?p=preview

Thanks,
Datta
