### ISSUE TITLE
Error while installion

### ISSUE THREAD

**Issue by garynhs** [mariuszfoltak/angular2-datatable#34]
I got following error while trying to install the package

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "-S" "angular2-datatable"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.8
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! angular2-datatable@0.4.2 postinstall: `cd src && typings install`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the angular2-datatable@0.4.2 postinstall script 'cd src && typings install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-datatable package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd src && typings install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-datatable
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-datatable
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/gary/npm-debug.log

**Comment by kafuikpoh** [comment]
i got the same error trying to push my app to heroku

**Comment by amm0nite** [comment]
It worked for me after doing `npm install typings --global`.
