### ISSUE TITLE
remote install error

### ISSUE THREAD

**Issue by kafuikpoh** [mariuszfoltak/angular2-datatable#35]
this is the error i get when i try to push my app to heroku:

remote:        > angular2-datatable@0.4.2 postinstall /tmp/build_3f84a6e31a33ca4f8575c1473072b869/node_modules/angular2-datatable
remote:        > cd src && typings install
remote:
remote:        sh: 1: typings: not found
remote:        cediwear.com@1.0.0 /tmp/build_3f84a6e31a33ca4f8575c1473072b869

**Comment by mariuszfoltak** [comment]
This bug was fixed in version 0.5.0. For version <0.4.2 you can install `typings` globally, `npm i -g typings`
