### ISSUE TITLE
Getting error angular2-datatable@0.4.2 postinstall: `cd src && typings install`

### ISSUE THREAD

**Issue by mehtak** [mariuszfoltak/angular2-datatable#40]
I am getting error [angular2-datatable@0.4.2 postinstall: `cd src && typings install`] while installing angular2-datatable@0.4.2 in my project. My colleagues are able to install the same without any problem. Notice, I cannot use any other version of angular2-datatable nor can I use any alternate library. I have to work with this version only.

**Comment by Tuupertunut** [comment]
You need to have `typings` package installed in your project. It is not listed in `peerDependencies` for some reason.

**Comment by mariuszfoltak** [comment]
It was a bug, `typings` shouldn't be required and it has been removed in v0.5.0.
In version below 0.5.0 you need to install `typings` globally, like @Tuupertunut said.
