### ISSUE TITLE
Cannot sort more then one level deep in data

### ISSUE THREAD

**Issue by mccs0064** [mariuszfoltak/angular2-datatable#41]
there is no way to sort data when it is more then one level deep.  For Example:

`<table class="table table-striped table-bordered table-hover" [mfData]="customerList" #mf="mfDataTable" [mfRowsOnPage]="10" cellspacing="0" width="100%">
    <thead>
    <tr>
        <th><mfDefaultSorter by="firstname">First Name</mfDefaultSorter></th>
        <th><mfDefaultSorter by="lastName">Last Name</mfDefaultSorter></th>
        <th><mfDefaultSorter by="mobilePhoneNumber">Phone Number</mfDefaultSorter></th>
        <th><mfDefaultSorter by="postal">Postal Code</mfDefaultSorter></th>
        <th><mfDefaultSorter by="postal">Number Of Vehicles</mfDefaultSorter></th>
        <th><mfDefaultSorter by="subscription">Subscription Type</mfDefaultSorter></th>
        <th><mfDefaultSorter by="subscriptionDate">Subscription Date</mfDefaultSorter></th>
    </tr>
    </thead>
    <tbody>
    <tr *ngFor="let user of mf.data">
        <td><a [routerLink]="['/customers', user.id]">{{user.firstName}}</a></td>
        <td>{{user.lastName}}</td>
        <td>{{user.mobilePhoneNumber}}</td>
        <td>{{user.addresses.HOME.postalCode}}</td>
        <td>{{user.vehicles.length}}</td>
        <td>{{user.subscription.name}}</td>
        <td>{{user.subscriptionDate}}</td>
    </tr>
    </tbody>
</table>`

i cannot sort by user.subscription.name or user.addresses.HOME.postalCode

**Comment by mariuszfoltak** [comment]
Fixed in v0.5.1
