### ISSUE TITLE
Custom functions in sortBy?

### ISSUE THREAD

**Issue by amellnik** [mariuszfoltak/angular2-datatable#47]
Should I be able to do something like 

``` javascript
<th><mfDefaultSorter by="[function(o) { return o.user; }]">User</mfDefaultSorter></th>
```

or are only column names supported?  (This is a trivial example -- I need to modify the sorting function to display nulls last for both ascending and descending sorts).

**Comment by mariuszfoltak** [comment]
Yes, you can pass function to sorter. You can check [examples/systemjs/app/app.component.ts](https://github.com/mariuszfoltak/angular2-datatable/blob/master/examples/systemjs/app/app.component.ts) (look at `sortByWordLength` function) for example.

**Comment by mariuszfoltak** [comment]
Example, I was wrote about, not working (function `sortByWordLength` is never used), but you can check it in [this plunker](http://plnkr.co/edit/aKCiSclZFpcmZotK9J3y?p=preview). Function `sortByWordLength` is used for `city` sorter

**Comment by amellnik** [comment]
Thanks @mariuszfoltak!  

In case anyone else looks at this issue later -- if you have dynamic columns it's also possible to dynamically define the sort functions.  For example:

In `component-name.component.ts`:
```typescript
  private sortFnClosure(colName:string) {
    return new Function('a', `return a['${colName}'].length;`);
  }
```

In `component-name.component.html`
```html
<thead><tr>
  ...
  <th *ngFor="let col of cols">
    <mfDefaultSorter [by]="sortFnClosure(col)">
      col
    </mfDefaultSorter>
  </th>
</tr></thead>
```

**Comment by priyankakolee** [comment]
Here we can edit the sortBy, any way to edit the sortOrder? I wish to make column sorting to be descending by default, on first click column should be sorted descending instead of ascending(which is default).
