### ISSUE TITLE
Search is CaSe sensitive.

### ISSUE THREAD

**Issue by nigel-dewar** [mariuszfoltak/angular2-datatable#51]
When using, the term used for searching must be entered exactly Case sensitive,

please make it so user can enter search term and ignore case. make case insenstive

Cheers

**Comment by mariuszfoltak** [comment]
For searching you need to create your own filter as pipe or function, and then pass it to mfData, e.g. `<table [mfData]="someData | yourFilterPipe" ...`.

**Comment by nigel-dewar** [comment]
Ok cool np.


Sent from Samsung Mobile


-------- Original message --------
From: Mariusz Foltak
Date:16/11/2016 17:10 (GMT+10:00)
To: mariuszfoltak/angular2-datatable
Cc: nigel-dewar , Author
Subject: Re: [mariuszfoltak/angular2-datatable] Search is CaSe sensitive. (#51)


For searching you need to create your own filter as pipe or function, and then pass it to mfData, e.g. <table [mfData]="someData | yourFilterPipe" ....

-
