### ISSUE TITLE
Sort icon

### ISSUE THREAD

**Issue by fpmk** [mariuszfoltak/angular2-datatable#53]
Is it possible to add "Sort" icon, when no sorting selected, but column is sortable ?

something like this

`
<span *ngIf="isSortedByMeAsc" class="glyphicon glyphicon-triangle-top" aria-hidden="true"></span>
<span *ngIf="isSortedByMeDesc" class="glyphicon glyphicon-triangle-bottom" aria-hidden="true"></span>
<span *ngIf="!isSortedByMeDesc && !isSortedByMeAsc" class="glyphicon glyphicon-sort" aria-hidden="true"></span>
`

**Comment by robguijt** [comment]
Other feature request based on same item. Is it possible to manage the sort icon in a css class, not directly referencing to a glyphicon font. In our project we use font-awesome for or sort icons. 
i.e.
`<span *ngIf="isSortedByMeAsc" class="sortorder desc" aria-hidden="true"></span> <span *ngIf="isSortedByMeDesc" class="sortorder asc" aria-hidden="true"></span> <span *ngIf="!isSortedByMeDesc && !isSortedByMeAsc" class="sortorder" aria-hidden="true"></span>`

**Comment by mariuszfoltak** [comment]
Hi,
For now the only thing you can do is create your own sorter, e.g:
```typescript
import {Component, Input} from "@angular/core";
import {DataTable} from "angular2-datatable";

@Component({
    selector: 'mySorter',
    template: `<a style="cursor: pointer" (click)="sort()" class="text-nowrap">
            <ng-content></ng-content>
            <span *ngIf="isSortedByMeAsc" class="glyphicon glyphicon-triangle-top" aria-hidden="true"></span>
            <span *ngIf="isSortedByMeDesc" class="glyphicon glyphicon-triangle-bottom" aria-hidden="true"></span>
            <span *ngIf="!isSortedByMeAsc && !isSortedByMeDesc" class="glyphicon glyphicon-sort" aria-hidden="true"></span>
        </a>`
})
export class MySorterComponent implements ngOnInit {
    @Input("by") sortBy: string;
    isSortedByMeAsc: boolean = false;
    isSortedByMeDesc: boolean = false;

    public constructor(private mfTable: DataTable) {
    }

    public ngOnInit(): void {
        this.mfTable.onSortChange.subscribe((event: SortEvent) => {
            this.isSortedByMeAsc = (event.sortBy == this.sortBy && event.sortOrder == "asc");
            this.isSortedByMeDesc = (event.sortBy == this.sortBy && event.sortOrder == "desc");
        });
    }

    sort() {
        if (this.isSortedByMeAsc) {
            this.mfTable.setSort(this.sortBy, "desc");
        } else {
            this.mfTable.setSort(this.sortBy, "asc");
        }
    }
}
```

**Comment by fpmk** [comment]
it's good, thanks

**Comment by cornelius-agrippa** [comment]
I made it by overriding the glyphicon class. I my case I'm using Ionic 3, which uses [Ionicons ](https://ionicframework.com/docs/ionicons/), so I ended up doing:

```
/* Hack to override glyphicons lol */
.glyphicon {
  display: inline-block;
  font-family: 'Ionicons';
  -moz-osx-font-smoothing: grayscale;
  -webkit-font-smoothing: antialiased;
  font-size: 1.0em;
  font-style: normal;
  font-variant: normal;
  font-weight: normal;
  line-height: 1;
  text-rendering: auto;
  text-transform: none;
}

.glyphicon::before {
  font-family: 'Ionicons';
  font-style: normal;
  font-variant: normal;
  font-weight: normal;
  line-height: 1;
  text-rendering: auto;
  text-transform: none;
  display: inline-block;
}

.glyphicon-triangle-top::before {
  content: "\f28b";
}

.glyphicon-triangle-bottom::before {
  content: "\f289";
}
```

The process should be similar for other unicode typefaces/icon libraries like font-awesome. Pay attention to the attributes `font-family:`, which should reflect the name of your library ('FontAwesome', for example) and replace the attribute `content:` with whichever unicode represents the icon you want to use.

**Comment by pratiksha-chandel** [comment]
Hello There , 
    I want to change icon on sorting .
      1]  As sending sorting will show ascending arrow .
      2] As descending sorting will show descending arrow .   
      3] For filter data filter icon will display . 
 How can I do with this.  
   @mariuszfoltak 
       I have tried with your solution but not working fro me 
Facing error :  mfTable not a member of -- component .
                        this.mfTable.onSortChange              : not a component member
                         this.mfTable.setSort(this.sortBy, "desc");: not a component member and supplied parameter not match .

Any other solution for that? help please !

**Comment by pratiksha-chandel** [comment]
![screenerror](https://user-images.githubusercontent.com/22052112/34667344-a3dcb62a-f48e-11e7-9ead-4d82a1b36fb9.png)
Facing this issue
