### ISSUE TITLE
Add responsive behavior to table

### ISSUE THREAD

**Issue by nitslucky** [mariuszfoltak/angular2-datatable#54]
Hi,
I tried the example and it worked perfectly. But when I am trying to add responsive class to table the responsive behavior did not work with it. Maybe I am doing something wrong could you please help me with this.

Thanks
![datatable-responsive](https://cloud.githubusercontent.com/assets/23555070/20431888/d0c55c62-ad9c-11e6-8ee3-ab297628c904.PNG)

**Comment by mariuszfoltak** [comment]
Hi, this issue is not related with datatable, but css and bootstrap framework. You should ask your question in bootstrap repository, because I don't know how to help you.
