### ISSUE TITLE
No sorting arrows display on columns

### ISSUE THREAD

**Issue by gciluffo** [mariuszfoltak/angular2-datatable#56]
@mariuszfoltak 
I copied code from the plunkr example of the DataTable into my Angular CLI project from: http://plnkr.co/edit/PxBaZs?p=preview. The table works great, all I did was alter the columns to fit my data. However there are no sorting arrows on the column headers, even though when you click on them they still sort. Here is what my table looks like.

![screen shot 2016-11-22 at 11 46 50 am](https://cloud.githubusercontent.com/assets/14182616/20537191/663dbde8-b0a9-11e6-96c6-571cf67fc7b8.png)

And here is what the plunkr example looks like. Notice the arrow on the email column.

![screen shot 2016-11-22 at 11 50 31 am](https://cloud.githubusercontent.com/assets/14182616/20537344/075297a8-b0aa-11e6-8fcc-60801aa32090.png)

Heres the html:

<div class="container-fluid">
    <div class="col-xs-12 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">

        <div class="row">
            <h2 class="col-xs-6 transfers-title">Transfers: Recent(20)</h2>
        </div>

        <div>
            <button class="btn bulk-update-selected-button" (click)="updateSelected()">Bulk Update Selected</button>
        </div>

        <div class="panel panel-default">

            <table class="table table-striped" [mfData]="transfers" #mf="mfDataTable"
                   [mfRowsOnPage]="20" [(mfSortBy)]="followup">
                <thead>
                <tr>
                    <th style="width: 10%">
                        <input type="checkbox"
                               name="options"
                               (change)="selectAll($event)"/>
                    </th>
                    <th style="width: 10%">
                        <mfDefaultSorter by="followup">Follow-up</mfDefaultSorter>
                    </th>
                    <th style="width: 40%">
                        <mfDefaultSorter by="accountNumber">Acct Number</mfDefaultSorter>
                    </th>
                    <th style="width: 30%; min-width: 200px">
                        <mfDefaultSorter by="clientName">Client Name</mfDefaultSorter>
                    </th>
                    <th style="width: 10%">
                        <mfDefaultSorter by="code">Code</mfDefaultSorter>
                    </th>
                    <th style="width: 10%">
                        <mfDefaultSorter by="type">Type</mfDefaultSorter>
                    </th>
                    <th style="width: 10%">
                        <mfDefaultSorter by="custodian">Custodian</mfDefaultSorter>
                    </th>
                    <th style="width: 10%">
                        <mfDefaultSorter by="created">Created</mfDefaultSorter>
                    </th>
                    <th style="width: 10%">
                        <mfDefaultSorter by="status">Status</mfDefaultSorter>
                    </th>

                    
                </tr>
                </thead>
                <tbody>
                <tr *ngFor="let item of mf.data">
                    <td>
                        <input type="checkbox"
                               name="options"
                               [(ngModel)]="item.checked"/>
                    </td>
                    <td>{{item.followup | date: 'dd/MM/yyyy'}}</td>
                    <td>{{item.accountNumber}}</td>
                    <td>{{item.clientName}}</td>
                    <td>{{item.code}}</td>
                    <td>{{item.type}}</td>
                    <td>{{item.custodian}}</td>
                    <td>{{item.created | date: 'dd/MM/yyyy'}}</td>
                    <td>{{item.status}}</td>
                </tr>
                </tbody>
                <tfoot>
                <tr>
                    <td colspan="5">
                        <mfBootstrapPaginator [rowsOnPageSet]="[5,10,15]"></mfBootstrapPaginator>
                    </td>
                </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>

Any else run into this issue? Thanks in advance.

**Comment by JustinSchneider** [comment]
@gciluffo Are you using Bootstrap 4? If so, Glyphicons are no longer included. I fixed this by extending the Glyphicons with their font-awesome equivalents using [this solution](http://stackoverflow.com/a/26638216) as a guide.
