### ISSUE TITLE
RXJS is not calling from node_module folder 

### ISSUE THREAD

**Issue by lkc513** [mariuszfoltak/angular2-datatable#6]
Hi,

That's a 404 error unable to find the RXJS *.js files. 
Afrer moved the RXJS Lib folder outside the node_module only able to detect. 

May i know this is a bug or a standard structure? 

404 GET /rxjs/Subject.js
404 GET /rxjs/observable/PromiseObservable.js
404 GET /rxjs/operator/toPromise.js
404 GET /rxjs/Observable.js
404 GET /rxjs/Subject.js
404 GET /rxjs/observable/PromiseObservable.js
404 GET /rxjs/operator/toPromise.js
404 GET /rxjs/Observable.js

Thank You

**Comment by mariuszfoltak** [comment]
Hi,
What bundling tool you use (systemjs, commonjs)? Can you post your configuration?

**Comment by lkc513** [comment]
Shld be using systemJS as refer to my package

`{
	"name": "angular2-quickstart",
  	"version": "1.0.0",
  	"scripts": {
		"start": "concurrently \"npm run tsc:w\" \"npm run lite\" ",
    	"tsc": "tsc",
    	"tsc:w": "tsc -w",
    	"lite": "lite-server",
    	"typings": "typings",
    	"postinstall": "typings install"
  	},
  	"license": "ISC",
  	"dependencies": {
    	"angular2": "2.0.0-beta.15",
    	"angular2-datatable": "0.2.6",
    	"es6-class-mixin": "1.0.5",
    	"es6-shim": "0.35.0",
    	"http.min": "^1.2.4",
    	"jquery": "2.2.3",
    	"lodash": "^4.11.1",
    	"reflect-metadata": "0.1.2",
    	"rxjs": "5.0.0-beta.2",
    	"systemjs": "0.19.26",
    	"zone.js": "0.6.10"
  	},
  	"devDependencies": {
		"concurrently": "^2.0.0",
    	"lite-server": "^2.2.0",
    	"nodemon": "^1.9.1",
    	"typescript": "^1.8.10",
    	"typings": "^0.7.12"
	}
}
`

**Comment by mariuszfoltak** [comment]
You should map rxjs in systemjs.config to 'node_modules/rxjs', http://stackoverflow.com/questions/34318885/how-to-load-rxjs-and-zone-js-reflect-metadata-with-angular-2-beta-and-newer

You can use block code, https://guides.github.com/features/mastering-markdown/
