### ISSUE TITLE
How to display the index number?

### ISSUE THREAD

**Issue by dreweird** [mariuszfoltak/angular2-datatable#60]
This is a very simple question but i can't find any example using angular2...thanks

**Comment by dreweird** [comment]
My bad...I found the answer

**Comment by lginq** [comment]
How you did it? 
Right now my index doesn't change when I change the page, it is always 1-10 on every page.

I have: 
```
<tr *ngFor="let item of mf.data; let idx = index">
                <td>{{idx+1}}</td>
</tr>
```
