### ISSUE TITLE
custom row name in dataFilter pipe

### ISSUE THREAD

**Issue by julioaze** [mariuszfoltak/angular2-datatable#73]
Hello, how can I use a dynamic row name in my pipe?
I need to use the pipe in several tables and I do not want to create a pipe for each of them.

thanks.

`import * as _ from "lodash";
import {Pipe, PipeTransform} from "@angular/core";

@Pipe({
    name: "dataFilter"
})
export class DataFilterPipe implements PipeTransform {

    transform(array: any[], query: string): any {
        if (query) {
            return _.filter(array, row=>row.DINAMIC.indexOf(query) > -1);
        }
        return array;
    }
}`

**Comment by dhagan** [comment]
`[mfData]="data| dataFilter :  filterQuery : 'lastName'"`

`import * as _ from "lodash";
import {Pipe, PipeTransform} from "@angular/core";

@Pipe({
    name: "dataFilter"
})
export class DataFilterPipe implements PipeTransform {

    transform(array: any[], query: string, field: string): any {
        if (query) {
            let ret =  _.filter(array, row=>row[field].indexOf(query) > -1);
            console.log(ret);
            return;
        }
        return array;
    }
`

**Comment by tbiinfotech** [comment]
By using your solution, I am getting result as array from data-filter.pipe file BUT my grid list is not getting update. Can you please suggest what changes I should do in component.html file or component.ts file?
