### ISSUE TITLE
[ERROR] Required is not defined

### ISSUE THREAD

**Issue by RicardoVaranda** [mariuszfoltak/angular2-datatable#9]
I keep getting a:

ReferenceError: require is not defined(…)

When I add the following directive

directives : [DataTableDirectives]

Are you using require for something in the module?

EDIT:

Btw I am using Systemjs but I have included the script for it in index.html so it should have a reference to it.

**Comment by mariuszfoltak** [comment]
Hi,
Yes, systemjs use require to load modules. It should work, but you should remove script tag with reference to DataTable js file and add it in systemjs config, like this:

```html
    <script>
        System.config({
            defaultJSExtensions: true,
            packages: {
                "/angular2": {"defaultExtension": false}
            },
            map: {
                'angular2-datatable': 'node_modules/angular2-datatable',
                'lodash': 'node_modules/lodash/lodash.js'
            }
        });
    </script>
```
