### ISSUE TITLE
ERROR in DataTableModule is not an NgModule

### ISSUE THREAD

**Issue by nandhuems** [mariuszfoltak/angular2-datatable#91]
First Compile its loading with error, anything change inside the code again its re-compile working fine. what is a problem?

**Comment by mashhoodr** [comment]
Getting the following error with Angular 4.0

```
ERROR in Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in ../node_modules/angular2-datatable/node_modules/@angular/core/src/metadata/ng_module.d.ts, resolving symbol NgModule in ../node_modules/angular2-datatable/node_modules/@angular/core/src/metadata.d.ts, resolving symbol NgModule in ../node_modules/angular2-datatable/node_modules/@angular/core/src/core.d.ts, resolving symbol NgModule in ../node_modules/angular2-datatable/node_modules/@angular/core/index.d.ts, resolving symbol DataTableModule in ../node_modules/angular2-datatable/lib/DataTableModule.d.ts, resolving symbol DataTableModule in ../node_modules/angular2-datatable/lib/DataTableModule.d.ts
```

**Comment by trevex** [comment]
`angular2-datatable` is not AoT compatible at the moment, see point 8 here: https://medium.com/@isaacplmann/making-your-angular-2-library-statically-analyzable-for-aot-e1c6f3ebedd5#.wmaqchqya

You can apply the changes locally to successfully compile:
Simply change `angular2-datatable`s `@angular/*` dependencies to peer-dependencies and delete the `@angular` folder within `node_modules/angular2-datatable/node_modules`.

**Comment by trevex** [comment]
I submitted a PR https://github.com/mariuszfoltak/angular2-datatable/pull/93, but for people like me who need an instant fix to continue with the migration to ng 4.0. You could temporarily use my fork from github directly by changing your `package.json` as following: 
`"angular2-datatable": "github:trevex/angular2-datatable#build",`

NOTE: I will delete the fork once the changes hit master and are published to npm!

**Comment by htrex** [comment]
I'm seeing this problem upgrading from Angular 2.4.10 to 4.0.0.
@travex build works, please merge PR #93 and publish to npm, thanks.

**Comment by nandhuems** [comment]
Hi thanks Everyone. i resolved the error. just upgrade my angularcli. now working fine

**Comment by mariuszfoltak** [comment]
Solved in v0.6.0, many thanks to @trevex

**Comment by stirumala76** [comment]
v0.6.0 I am not seeing this version, issue did not resolve

**Comment by okpablo** [comment]
Just replace in app.module.ts: 
`import { DataTableModule } from 'angular-4-data-table';`
with
`import { DataTableModule } from 'angular-4-data-table/src/index';`
